### ISSUE TITLE
Theme's Operations

### ISSUE THREAD

**Issue by LivyChops** [Jetski5822/ACMEMedicalTheme#2]
"...Thanks for replying to the codeplex thread, Nick - excuse the copy and paste"
Hmm, I hope I'm not being incredibly stupid – _but here goes_...will this work straight out of the box if I was to create a <page> with an <area> “Member” selected (also with a visually different site-member.css file to the default), so that when I browse to the newly created page – should it not alter/replace the default css with the site-member.css? If this is the case, for some reason - referring to the code in Views > Resources.html - "WorkContext.IsMemberRequest()" never returns "true" with the pages I'm creating with Member selected, or any of the default site areas for that matter?
Or do I have your code's intent completely wrong _blush_? Any assistance would be great, as I’m stumped – big thanks, Liv.

**Comment by Jetski5822** [comment]
Yes, the idea is that the different CSS is shown based on taxonomy of 'Area' So in you tag a page with Member then your page will show site-member.css.

IsMemberRequest() will return true when you have tagged a page as a member page, are you saying that doesnt work when you browse to a page that is tagged member?

**Comment by LivyChops** [comment]
Yeah - setting a page to any of the default terms [Member for e.g.] doesn't evaluate true when using IsMemberRequest()? Utilising the template code in Resources.cshtml, anyway.
Am I missing something obvious, or perhaps something has been accidentally removed? I'm going to try a few more things today, so hopefully I'll have some more clues for you. Thanks for the reply and any thoughts, regards Liv

**Comment by Jetski5822** [comment]
@LivyChops I have pushed a few updates to update it 1.9, so you should be able to compile it now. I tested locally and it all works.

**Comment by Jetski5822** [comment]
@LivyChops Oh, and make sure that  the theme lives in the folder ACME.Theme.Medical, so:

git clone https://github.com/Jetski5822/ACMEMedicalTheme.git ACME.Theme.Medical

**Comment by dyrgutt** [comment]
Hey Nick, sorry I havent gotten around to checking your Theme until now, but I believe LivyChops issue is due to local development.

The requestPath var in 'GetAreaName' will always return 'OrchardLocal/pagename'

So I just made this quick and nasty edit:

```
        var requestPath = workContext.HttpContext.Request.Path.ToLowerInvariant(); //.TrimStart('/').ToLowerInvariant();

        int index = requestPath.LastIndexOf('/');

        if (index >= 0)
        {
            requestPath = requestPath.Substring(index + 1);
        }
```

and it should work as expected [as i'm sure it does on a live site ;) ]

Anyhow, I will try and give the theme a proper run tomorrow, but all looks great - Thanks for all your efforts, mate - welldone!

**Comment by LivyChops** [comment]
@dyrgutt Oh?! Thank you so, so, much! It works with those amendments :) ...going to give the theme a good test; 'I'll let you know how I get on.' Thanks ever so much, guys - really love the Orchard community and the inspirational work of its members: @Jetski5822 . Big respect to you both, Liv.

**Comment by dyrgutt** [comment]
Nick will be able to tell you more, but you may also have to change some other blocks regarding that issue -- and please test that code thoroughly, @LivyChops , and perhaps await @Jetski5822 advice as i'm only making assumptions on his code of which I'm not familiar; besides, at best - i'm just a hack and nowhere near the league of Nick. Have fun and happy coding.

**Comment by Jetski5822** [comment]
Thanks for the Kudos peeps!... I have pushed a fix today to deal with issue mentioned above.

https://github.com/Jetski5822/ACMEMedicalTheme/commit/2dccdfad2259f2dacba2e564a259eee5b85c32f5
