### ISSUE TITLE
Layer rules bug

### ISSUE THREAD

**Issue by dyrgutt** [Jetski5822/ACMEMedicalTheme#3]
Hey Nick, had a bit more of a playaround this morning, only bug I noticed, was:

Enabling theme disrupts all other layer rules a user may've implemented due to "sitearea's" ruleContext.Result = false...

Changing to the following should sort it. 

```
    public void Process(RuleContext ruleContext) {
        if (!String.Equals(ruleContext.FunctionName, "sitearea", StringComparison.OrdinalIgnoreCase))
            return;

        var argument = ((object[])ruleContext.Arguments)
            .Cast<string>()
            .Single();


ruleContext.Result = _workContext.IsAreaRequest(argument);
       //ruleContext.Result = false;
    }
```

Other than this, you've given me a lot of food for thought - still not 100% sure which way i'll go; but due to your solution, i'm now at 95% ;)  So thanks for the great foundation and all your support, cheers Peter.

**Comment by Jetski5822** [comment]
Ahhh - I had this fixed in another internal theme... forgot to push it to this one! Push my local code. - Thanks for pointing out.
